# Generated by Django 5.2.9 on 2025-12-18 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Canton",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ciudad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Provincia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "rol",
                    models.CharField(
                        choices=[("admin", "Administrador"), ("user", "Usuario")],
                        default="user",
                        max_length=20,
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "canton",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.canton",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="canton",
            name="ciudad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.ciudad"
            ),
        ),
        migrations.AddField(
            model_name="ciudad",
            name="provincia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.provincia"
            ),
        ),
        migrations.CreateModel(
            name="Tacho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("publico", "Público / Empresa"),
                            ("personal", "Personal"),
                        ],
                        default="publico",
                        max_length=20,
                    ),
                ),
                ("ubicacion_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("ubicacion_lon", models.DecimalField(decimal_places=6, max_digits=9)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("mantenimiento", "Mantenimiento"),
                            ("fuera_servicio", "Fuera de servicio"),
                        ],
                        default="activo",
                        max_length=20,
                    ),
                ),
                ("nivel_llenado", models.IntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "propietario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tachos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Deteccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clasificacion",
                    models.CharField(
                        choices=[
                            ("organico", "Orgánico"),
                            ("inorganico", "Inorgánico"),
                            ("reciclable", "Reciclable"),
                            ("ninguno", "No clasificado"),
                        ],
                        default="ninguno",
                        max_length=20,
                    ),
                ),
                (
                    "confianza_ia",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("imagen", models.ImageField(upload_to="detecciones/%Y/%m/%d/")),
                ("ubicacion_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("ubicacion_lon", models.DecimalField(decimal_places=6, max_digits=9)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("procesado", models.BooleanField(default=True)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detecciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tacho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detecciones",
                        to="core.tacho",
                    ),
                ),
            ],
        ),
    ]
