# Generated by Django 5.2.9 on 2026-01-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tacho",
            name="empresa_nombre",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Nombre de la empresa/institución",
            ),
        ),
    ]
